# -*- coding: utf-8 -*-
"""Service copy for the AI AutoTech redesign. Plain English, no invented results."""

WHO_KEYS = [
    ("clinic", "Clinics & practices"),
    ("school", "Schools & colleges"),
    ("estate", "Estate agents"),
    ("broker", "Brokers & advisers"),
    ("service", "Service businesses"),
]

SERVICES = [
  dict(slug="ai-employees", name="AI Employees & Agents", short="AI Employees", icon="bot", tone="t",
    sub="Handle the busy work so your team can focus on what matters.",
    card="Trained AI agents that answer, follow up, book and do admin, 24/7.",
    lead="An AI employee is a trained AI agent with one clear job: answering enquiries, following up leads, booking appointments or doing admin. It works inside the tools you already use, day and night, and hands over to a person when it should.",
    price="From R8,999/month (excl. VAT)", price_num="8999", mock="roster",
    title="AI Employees & Agents for South African Businesses | AI AutoTech",
    desc="Hire an AI employee from R8,999/month. AI agents that answer enquiries, follow up leads, book appointments and handle admin 24/7 for South African businesses.",
    steps=[
      ("Map the job", "We sit with you and write down exactly what the role does: which questions it answers, which tasks it completes and when it must hand over to a person."),
      ("Build & connect", "We train the agent on your prices, policies and FAQs, then connect it to WhatsApp, email, your calendar and your CRM."),
      ("Launch & supervise", "A soft launch with your team watching, then monthly reviews where we tune its answers and add new tasks as you grow."),
    ],
    gains=[
      "Enquiries answered in seconds, including evenings, weekends and public holidays",
      "Consistent answers based on your real prices, policies and service areas",
      "Every conversation logged, so nothing depends on someone's memory",
      "Clear hand-over to a person for complaints, sales closes and anything sensitive",
      "Extra capacity without recruitment, UIF, leave or weeks of training",
      "A flat monthly fee in Rand that you can budget for",
    ],
    who=dict(
      clinic="A front-desk agent that answers 'are you open?', 'do you take my medical aid?' and books consultation slots.",
      school="An admissions agent that explains programmes, fees and entry requirements and collects applicant details.",
      estate="A lead agent that qualifies buyers and tenants on budget, area and bond pre-approval before you call.",
      broker="An intake agent that gathers the details needed for a quote and politely chases missing documents.",
      service="A booking and quoting agent for plumbers, electricians, salons, repair shops and consultants.",
    )),
  dict(slug="whatsapp-automation", name="WhatsApp Automation", short="WhatsApp", icon="whatsapp", tone="t",
    sub="Capture leads, answer customers and close more sales on WhatsApp.",
    card="Instant replies, lead capture, reminders and one shared team inbox.",
    lead="Most South African customers would rather WhatsApp than phone or email. We turn your WhatsApp number into an organised sales and service channel: instant replies, lead capture, quick-reply menus, reminders and hand-over to your team, with every chat saved to your CRM.",
    price=None, mock="chat",
    title="WhatsApp Automation for South African Businesses | AI AutoTech",
    desc="Automate your WhatsApp Business inbox: instant replies, lead capture, booking, reminders and CRM integration, built in Benoni for South African businesses.",
    steps=[
      ("Set up the number properly", "WhatsApp Business Platform (Meta's official API), a verified business profile, and opt-in wording that respects POPIA."),
      ("Design the flows", "Greeting, menus, FAQ answers, lead questions, bookings and quotes, plus clear rules for when a person takes over."),
      ("Connect & launch", "Link to your CRM, calendar and website buttons, test with real scenarios, go live and review weekly for the first month."),
    ],
    gains=[
      "No more 'sorry for the late reply': the first response is instant",
      "Leads captured with name, need and budget before a person steps in",
      "Your whole team works from one shared inbox instead of personal phones",
      "Automatic reminders for appointments, quotes and payments using approved templates",
      "Every chat saved against the contact in your CRM",
      "Website, Google profile, adverts and QR codes all feed into the same flow",
    ],
    who=dict(
      clinic="Appointment booking, reminders the day before and 'what should I bring?' answers.",
      school="Enquiry menus for programmes, fees and open days, plus application follow-ups.",
      estate="Capture enquiries from portals and show-day QR boards and send available viewing times.",
      broker="Collect quote details and documents on WhatsApp instead of long email threads.",
      service="Quote requests with photos, booking confirmations and 'we're on our way' job updates.",
    )),
  dict(slug="ai-voice-agents", name="AI Voice Agents", short="Voice Agents", icon="voice", tone="v",
    sub="24/7 call answering and lead qualification.",
    card="Natural-sounding agents that answer calls, qualify and book, day and night.",
    lead="Never miss a call again. An AI voice agent answers your phone line in a natural voice, answers common questions, qualifies the caller, books the appointment and sends your team a written summary, even at 9pm on a Sunday.",
    price="From R14,999/month (excl. VAT)", price_num="14999", mock="voice",
    title="AI Voice Agents: 24/7 Call Answering | AI AutoTech South Africa",
    desc="AI voice agents from R14,999/month: 24/7 call answering, lead qualification and appointment booking for South African businesses. Built in Benoni, Gauteng.",
    steps=[
      ("Script & voice", "We write the call flow with you: the greeting, the questions to ask, what it may and may not say, and when to transfer to a person."),
      ("Connect your line", "Call forwarding or a dedicated number, linked to your calendar and CRM, with after-hours and overflow rules."),
      ("Test & go live", "We run test calls with you until it sounds right, then launch and review the call summaries with you every week at first."),
    ],
    gains=[
      "Calls answered after hours, over lunch and when everyone is busy",
      "Every caller qualified with the same questions, every time",
      "Appointments booked straight into your calendar",
      "A written summary and transcript of every call, sent to your team",
      "Urgent calls transferred to a person immediately",
      "Optional outbound follow-up and reminder calls, within POPIA and consent rules",
    ],
    who=dict(
      clinic="After-hours and overflow calls, bookings and 'is the doctor in today?' questions.",
      school="The flood of parent calls during admissions season, plus open-day bookings.",
      estate="Answer every call from boards and listings, qualify the caller and book the viewing.",
      broker="First-contact calls that capture what cover is needed and the best callback time.",
      service="Emergency call-outs, quote requests and booking confirmations, 24/7.",
    )),
  dict(slug="crm-pipelines", name="CRM & Pipelines", short="CRM & Pipelines", icon="crm", tone="t",
    sub="Organise leads, close more.",
    card="Every lead in one pipeline, with automatic follow-ups.",
    lead="Never lose a lead. Every enquiry from WhatsApp, your website, forms, calls and social media lands in one pipeline, with automatic follow-ups and a clear view of what is about to close.",
    price=None, mock="kanban",
    title="CRM & Pipelines: Organise Leads, Close More | AI AutoTech",
    desc="CRM and sales pipelines set up for South African businesses: WhatsApp, website and form leads in one place, automatic follow-ups and clear dashboards.",
    steps=[
      ("Connect sources", "WhatsApp, website forms, email, calls and ad leads flow into one CRM, with duplicates merged."),
      ("Build pipeline & automations", "Stages that match how you actually sell, auto-assignment, follow-up reminders and nurturing messages."),
      ("Launch & train", "We onboard your team, set up dashboards and review the numbers with you after the first month."),
    ],
    gains=[
      "No enquiry lost in someone's personal phone or inbox",
      "Faster follow-ups with automatic reminders and replies",
      "Your full pipeline visible at a glance",
      "Know which marketing channel actually brings paying clients",
      "Notes, tasks and messages logged automatically, so less admin",
      "Owners see the numbers without chasing staff for updates",
    ],
    who=dict(
      clinic="Track new-patient enquiries from first message through to the first visit.",
      school="Applicants from enquiry to enrolment, with a document checklist per student.",
      estate="Buyers, sellers and tenants in separate pipelines with viewing follow-ups.",
      broker="Quotes, renewals and cross-sell opportunities with reminder dates.",
      service="Quotes sent, accepted and invoiced, so you always know what is outstanding.",
    )),
  dict(slug="ai-chat-voice", name="AI Chat + Voice", short="AI Chat + Voice", icon="chat", tone="v",
    sub="Natural conversations that sell and support, on every channel.",
    card="One assistant for web chat, WhatsApp, social and voice notes.",
    lead="One AI assistant for your website chat, WhatsApp and social inboxes. It understands typed messages and voice notes, answers from your own information, recommends the right product or service and books the next step.",
    price=None, mock="webchat",
    title="AI Chat + Voice Assistant for Websites & WhatsApp | AI AutoTech",
    desc="An AI assistant for website chat, WhatsApp and social media that understands voice notes, answers from your own information and books the next step.",
    steps=[
      ("Gather your knowledge", "Price lists, FAQs, brochures, policies and past chats become the assistant's knowledge base, reviewed by you."),
      ("Deploy on your channels", "Website chat widget, WhatsApp, Facebook and Instagram messages, with voice-note understanding switched on."),
      ("Measure & improve", "We review conversations, fix gaps in answers and add new topics every month."),
    ],
    gains=[
      "Visitors get answers without waiting for office hours",
      "Voice notes understood and answered, not left for later",
      "The same accurate answers across web, WhatsApp and social",
      "Smart hand-over with the full conversation, so customers never repeat themselves",
      "Questions it could not answer are reported, so you can fill the gaps",
      "Fewer repetitive questions landing on your staff",
    ],
    who=dict(
      clinic="Pre-visit questions, medical aid queries and preparation instructions.",
      school="Prospective students asking about courses late at night, when they actually browse.",
      estate="Listing questions and viewing requests coming in from portals and social media.",
      broker="Explaining cover options in plain language before a consultant calls back.",
      service="Product questions, price ranges and bookings straight from your website.",
    )),
  dict(slug="business-automation", name="Business Automation", short="Automation", icon="gear", tone="t",
    sub="Save time, reduce costs and remove manual processes.",
    card="Quotes, invoices, onboarding and reports that run themselves.",
    lead="We find the repetitive work that eats your week, like capturing data, sending quotes and invoices, onboarding clients, chasing documents and compiling reports, and automate it end to end with reliable, monitored workflows.",
    price=None, mock="flow",
    title="Business Automation for South African SMBs | AI AutoTech",
    desc="Automate quotes, invoices, client onboarding, document collection and reporting. Reliable, monitored workflows for South African businesses.",
    steps=[
      ("Process audit", "We map one or two workflows step by step with you and find where the time and errors actually happen."),
      ("Automate & integrate", "We build the workflow across your tools (email, spreadsheets, accounting, CRM, WhatsApp) with checks and error alerts."),
      ("Hand over & monitor", "We document how it works, train your team and monitor every run so failures are caught early."),
    ],
    gains=[
      "Hours of copy-and-paste admin removed every week",
      "Fewer errors from retyping data between systems",
      "Quotes, invoices and reminders sent on time, every time",
      "Client onboarding that runs the same way for every client",
      "Reports that build themselves and land in your inbox",
      "Staff freed up for work that needs a human",
    ],
    who=dict(
      clinic="Intake forms flowing into patient records, plus recall and follow-up reminders.",
      school="Applications, document checks and fee reminders without manual chasing.",
      estate="FICA document collection, listing admin and lead routing to the right agent.",
      broker="Quote comparisons, renewal reminders and document collection.",
      service="Job cards, quote-to-invoice and a review request after every completed job.",
    )),
  dict(slug="websites-dashboards", name="Websites & Dashboards", short="Websites", icon="monitor", tone="t",
    sub="Modern, fast, mobile-friendly websites that convert.",
    card="Fast sites with WhatsApp and booking built in, plus live dashboards.",
    lead="Your website should bring in enquiries, not just look nice. We build fast, mobile-first sites with WhatsApp, booking and lead capture built in, plus simple dashboards so you can see leads, bookings and sales in one place.",
    price=None, mock="dashboard",
    title="Websites & Dashboards for South African Businesses | AI AutoTech",
    desc="Fast, mobile-first business websites with WhatsApp, booking and lead capture built in, plus live dashboards. Built in Benoni, Gauteng.",
    steps=[
      ("Plan the pages", "Goals, audience, offers and the call to action for every page, agreed before any design starts."),
      ("Design & build", "Mobile-first design, fast hosting, SEO basics, WhatsApp and booking buttons, and forms connected to your CRM."),
      ("Launch & report", "We connect your domain, analytics and a live dashboard, then hand over with training."),
    ],
    gains=[
      "A site that loads quickly on mobile data",
      "Every form and WhatsApp click captured as a lead",
      "Google-friendly structure, page titles and descriptions",
      "Leads, bookings and sales in one dashboard",
      "Quick updates without waiting weeks for a developer",
      "Modern hosting with HTTPS as standard",
    ],
    who=dict(
      clinic="Services, practitioner profiles and online booking requests.",
      school="Programme pages, online applications and open-day registrations.",
      estate="Listings, valuation requests and agent profiles.",
      broker="Product explainers, quote requests and the compliance information you must show.",
      service="Service areas, quote forms and a gallery of completed work.",
    )),
  dict(slug="digital-transformation", name="Digital Transformation", short="Transformation", icon="trend", tone="t",
    sub="Future-ready systems for sustainable growth.",
    card="A phased move from paper and spreadsheets to connected systems.",
    lead="For businesses still running on paper, spreadsheets and memory. We plan and implement the move to connected digital systems step by step, without stopping your day-to-day operations.",
    price=None, mock="phases",
    title="Digital Transformation for South African SMBs | AI AutoTech",
    desc="Move from paper and spreadsheets to connected digital systems, CRM, automation and AI, in phases that fit South African small and medium businesses.",
    steps=[
      ("Assess & roadmap", "We review how work flows today and agree a phased plan with priorities, costs and timelines."),
      ("Implement in phases", "CRM, automation, WhatsApp and AI employees rolled out one piece at a time, with your data migrated safely."),
      ("Train & embed", "We train your staff, document procedures and support you until the new way of working sticks."),
    ],
    gains=[
      "A clear roadmap instead of a pile of random apps",
      "Paper and spreadsheets replaced by systems that talk to each other",
      "Owners see what is happening in the business in real time",
      "Processes that do not depend on one key person",
      "POPIA-aware handling of personal information",
      "A foundation that is ready for AI as you grow",
    ],
    who=dict(
      clinic="From paper files and phone diaries to digital booking and record workflows.",
      school="Digital applications, parent communication and reporting.",
      estate="From scattered WhatsApp chats to a structured CRM and listing process.",
      broker="Document management and consistent client communication.",
      service="Job management, quoting and invoicing in one connected flow.",
    )),
  dict(slug="research-specialist", name="Autonomous Research Specialist", short="Research Specialist", icon="research", tone="v",
    sub="Deep research, real sources, fact-checked.",
    card="An AI researcher that reads the sources and hands you a cited brief.",
    lead="An AI research agent that searches the web and your own documents, reads the sources, cross-checks the claims and delivers a cited brief. Use it for market research, competitor tracking, tenders, due diligence and content.",
    price=None, mock="research",
    title="Autonomous Research Specialist: Cited AI Research | AI AutoTech",
    desc="An autonomous AI research agent that searches, reads and fact-checks sources and delivers cited briefs for market research, competitors and tenders.",
    steps=[
      ("Define the research scope", "The questions, which sources to trust or exclude, the output format and how often you want updates."),
      ("Connect research tools", "Web research (for example Perplexity), your internal documents and databases, set up with sensible limits."),
      ("Deliver & verify", "Briefs with citations and a fact-check pass, delivered to email, Notion or your dashboard on schedule."),
    ],
    gains=[
      "A source link for every claim, so you can check it yourself",
      "Hours of manual searching reduced to a focused review",
      "Scheduled competitor and market updates",
      "A consistent report format your team can act on",
      "Flags where sources disagree or evidence is weak",
      "Human review kept in the loop for anything important",
    ],
    who=dict(
      clinic="New treatments, regulations and supplier comparisons.",
      school="Accreditation requirements, bursary and funding opportunities, competitor programmes.",
      estate="Area reports and market updates you can send to clients.",
      broker="Product comparisons and regulatory updates.",
      service="Tenders, supplier options and competitor pricing.",
    )),
  dict(slug="autonomous-orchestrator", name="Autonomous Orchestrator", short="Orchestrator", icon="hub", tone="v",
    sub="One command centre that coordinates your AI team.",
    card="The hub that assigns, checks and connects your AI agents.",
    lead="When you run several AI agents, something has to coordinate them. The orchestrator assigns tasks, passes context between agents, checks their work and escalates to a person when needed, so your AI team works as one.",
    price=None, mock="hex",
    title="Autonomous Orchestrator: Coordinate Your AI Agents | AI AutoTech",
    desc="An autonomous orchestrator that coordinates your AI agents: assigning tasks, sharing context, checking work and escalating to people when needed.",
    steps=[
      ("Design the team", "Decide which agents you need, what each one is allowed to do, and which actions need human approval."),
      ("Wire the hub", "Connect the agents to shared memory, your data (for example Supabase) and your business tools, with a log of every action."),
      ("Run, monitor & improve", "Daily activity summaries, approvals for sensitive actions and monthly tuning of the whole team."),
    ],
    gains=[
      "Multi-step work done end to end, not in isolated chats",
      "Every agent action logged and auditable",
      "Human approval exactly where it matters",
      "Agents share context, so nothing is asked twice",
      "Scales from two agents to a full AI department",
      "The right tool for each job, coordinated in one place",
    ],
    who=dict(
      clinic="Booking, reminder and reporting agents working from one schedule.",
      school="An admissions pipeline that spans chat, email and CRM.",
      estate="Lead sourcing, qualification and listing marketing agents working together.",
      broker="Intake, research and renewal agents sharing one client view.",
      service="Enquiry to quote to invoice, handled by a coordinated team.",
    )),
]

STACK = [
  ("Grok", "Gk", "Real-time signals"),
  ("Perplexity", "Px", "Cited web research"),
  ("Hermes", "He", "Agent memory"),
  ("Claude Code", "CC", "Planning & builds"),
  ("Codex", "Cx", "Code generation"),
  ("Cursor", "Cu", "AI code editor"),
  ("Supabase", "Sb", "Database & auth"),
  ("Vercel", "Ve", "Hosting & edge"),
]

ORCH_NODES = [
  ("Hunter", "Grok", "t"), ("Scout", "Perplexity", "v"), ("Keeper", "Hermes", "t"), ("Architect", "Claude Code", "v"),
  ("Builder", "Codex", "t"), ("Shipper", "Cursor", "v"), ("Vault", "Supabase", "t"), ("Edge Runner", "Vercel", "v"),
]

# Google Calendar booking (30-min Google Meet with Billy). /book/ embeds the appointment schedule.
BOOK = dict(
    label="Book a call",
    embed="https://calendar.google.com/calendar/appointments/schedules/AcZssZ380rFZVjLLzJxygU1WcJYYwIsbZDYcq8rg-tRx3LvJu8GVFKYYHmFEsAQZTwJzNRyMpZXFZ5UN?gv=true",
    google_page="https://calendar.app.google/CRRWqhvumHBbkwjFA",
    length="30 min",
    where="Google Meet",
    tz="SAST (Johannesburg)",
)

# ---------------- "Pick your AI team" (second front door next to the audit) ----------------
# Only known price: AI employees from R8,999/month. No invented prices, stats, testimonials or results.
TEAM_PRICE = "From R8,999/month"
TEAM_PRICE_NOTE = "excl. VAT. Final price depends on how many AI employees you start with and your setup; confirmed before any work starts."

TEAMS = [
  dict(slug="dental-front-desk", name="Dental Front Desk Team", short="Dental practices", icon="clinic", tone="t",
    title="Dental Front Desk AI Team | WhatsApp bookings, reminders & reviews | AI AutoTech",
    desc="An AI front desk for dental practices: answers patient WhatsApps 24/7, books appointments, sends reminders, chases no-shows and collects Google reviews. From R8,999/month.",
    pitch="Answers WhatsApps 24/7, books patients, sends reminders, chases no-shows and collects reviews.",
    lead="Your reception team stays focused on the patients in front of them. The AI team handles the messages, bookings, reminders and follow-ups around them, day and night, using your practice's own information and diary.",
    members=[
      ("whatsapp", "WhatsApp Receptionist", "Answers patient WhatsApps 24/7: hours, services, directions and common questions, using the information you approve."),
      ("calendar", "Booking Agent", "Offers open slots and books, moves or cancels appointments in your practice diary."),
      ("clock", "Reminder Agent", "Sends appointment confirmations and reminders so patients know when to arrive."),
      ("leads", "No-show Follow-up Agent", "Messages patients who missed or cancelled an appointment and offers a new time."),
      ("star", "Reviews Agent", "Asks patients for a Google review after their visit, with a direct link."),
    ],
    day=[
      ("21:40", "A patient WhatsApps about a sore tooth. The WhatsApp Receptionist replies straight away and the Booking Agent offers the first morning slot. Booked."),
      ("07:30", "The Reminder Agent sends today's reminders. One patient asks to move to the afternoon and gets rebooked."),
      ("10:15", "A patient doesn't arrive. The No-show Follow-up Agent messages them and offers two new times."),
      ("17:00", "The Reviews Agent sends a review link to patients seen today. A question about a medical aid claim is handed to your reception team."),
    ],
    fit=["General and family dental practices", "Practices with one or more chairs and a busy WhatsApp line", "Teams losing time to reminders and rebooking calls"],
    note="Review requests and patient messages are set up to fit your practice's policies and your professional body's rules.",
    wa="Hi Billy, I'd like to start with the Dental Front Desk Team for my practice."),
  dict(slug="estate-agent-leads", name="Estate Agent Lead Team", short="Estate agents", icon="estate", tone="v",
    title="Estate Agent AI Lead Team | Instant replies, qualified buyers & viewings | AI AutoTech",
    desc="An AI lead team for estate agents: replies to every property enquiry in seconds, qualifies buyers and renters, books viewings and follows up. From R8,999/month.",
    pitch="Replies to every property enquiry in seconds, qualifies buyers and renters, books viewings and follows up.",
    lead="Property enquiries arrive from portals, your website and WhatsApp at all hours. The AI team replies to every one in seconds, works out who is serious and gets viewings into your agents' calendars.",
    members=[
      ("chat", "Enquiry Responder", "Replies to portal, website and WhatsApp enquiries within seconds, with the listing details you've loaded."),
      ("leads", "Buyer & Renter Qualifier", "Asks the right questions (budget, area, bond pre-approval or move-in date) and tags each lead hot, warm or cold."),
      ("calendar", "Viewing Scheduler", "Books viewings into the right agent's calendar and sends the address and a reminder."),
      ("trend", "Follow-up Agent", "Follows up after viewings and keeps colder leads warm with new listings that match what they asked for."),
    ],
    day=[
      ("06:55", "A portal enquiry comes in for a 3-bedroom listing. The Enquiry Responder replies within seconds with the details and asks a few questions."),
      ("07:05", "The Buyer & Renter Qualifier learns the buyer has bond pre-approval and wants to move within three months, and tags them hot."),
      ("07:10", "The Viewing Scheduler books a Saturday 10:00 viewing in the listing agent's calendar and sends a reminder on Friday."),
      ("Monday", "The Follow-up Agent asks how the viewing went and shares two similar listings. The agent takes over for the offer."),
    ],
    fit=["Residential sales and rental agencies", "Agents getting leads from portals, social media and WhatsApp", "Teams where enquiries wait until an agent is free"],
    wa="Hi Billy, I'd like to start with the Estate Agent Lead Team for my agency."),
  dict(slug="college-admissions", name="College Admissions Team", short="Colleges & training", icon="school", tone="t",
    title="College Admissions AI Team | Course questions, applications & campus visits | AI AutoTech",
    desc="An AI admissions team for colleges and training providers: answers course and fee questions, collects applications and documents, follows up with applicants and books campus visits. From R8,999/month.",
    pitch="Answers course and fee questions, collects applications and documents, follows up with applicants and books campus visits.",
    lead="During intake season your admissions office gets the same questions hundreds of ways. The AI team answers them from your approved course information, guides applicants through the paperwork and keeps them moving to registration.",
    members=[
      ("chat", "Admissions Assistant", "Answers course, entry requirement and fee questions on WhatsApp and your website, from your approved information."),
      ("layers", "Application Collector", "Guides applicants through the application and collects documents such as ID copies and results."),
      ("leads", "Applicant Follow-up Agent", "Follows up incomplete applications and upcoming deadlines so applicants don't drop off."),
      ("calendar", "Campus Visit Scheduler", "Books campus visits and open-day slots and sends reminders."),
    ],
    day=[
      ("20:15", "A parent asks on WhatsApp about entry requirements and fees for a course. The Admissions Assistant answers from your approved course information."),
      ("20:20", "The applicant starts the application. The Application Collector asks for an ID copy and latest results."),
      ("Two days later", "The application is still missing one document. The Applicant Follow-up Agent sends a friendly reminder with the deadline."),
      ("Saturday", "The Campus Visit Scheduler books the family onto the open day. Anything about bursaries or exceptions goes to your admissions staff."),
    ],
    fit=["Private colleges, TVET-style and short-course providers", "Training academies with intakes and deadlines", "Admissions teams buried in repeat questions"],
    wa="Hi Billy, I'd like to start with the College Admissions Team for my college."),
  dict(slug="broker-client", name="Broker Client Team", short="Insurance & finance brokers", icon="broker", tone="v",
    title="Broker AI Client Team | Quote requests, documents & renewals | AI AutoTech",
    desc="An AI client team for insurance and financial brokers: handles quote requests, collects documents, sends renewal reminders and answers policy questions. From R8,999/month.",
    pitch="Handles quote requests, collects documents, sends renewal reminders and answers policy questions.",
    lead="Your brokers should spend their time advising clients, not chasing forms. The AI team handles the admin around every quote, renewal and policy question, and hands anything that needs advice to a licensed person.",
    members=[
      ("leads", "Quote Request Agent", "Captures quote requests with all the details your team needs and sends them to the right broker."),
      ("layers", "Document Collector", "Requests and chases documents such as ID copies, vehicle or property details and current schedules."),
      ("clock", "Renewal Reminder Agent", "Sends renewal reminders ahead of the date and books a review call with the broker."),
      ("chat", "Policy Q&A Assistant", "Answers common policy questions from wording you approve. It never gives advice; advice and claims questions go to your licensed staff."),
    ],
    day=[
      ("08:10", "A client asks on WhatsApp for a car insurance quote. The Quote Request Agent collects the vehicle, driver and cover details."),
      ("08:20", "The Document Collector asks for the ID copy and current schedule, and sends a reminder the next day for the missing one."),
      ("11:00", "The Renewal Reminder Agent contacts clients whose policies renew next month and books review calls with the broker."),
      ("15:30", "A client asks what their policy covers for a burst geyser. The Policy Q&A Assistant shares the approved wording and hands the claim to a broker."),
    ],
    fit=["Short-term insurance brokers", "Financial advisers and brokerages", "Practices with lots of renewals and document chasing"],
    wa="Hi Billy, I'd like to start with the Broker Client Team for my brokerage."),
]
